kind: SealedSecret
apiVersion: "bitnami.com/v1alpha1"
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
spec:
  data: {{ .Values.secrets.value.gdm | quote }}
